server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: userServer
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: SH    #集群HZ
        namespace: eebfde3b-c5ec-4c6f-8648-36282a9020d7
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
    #fetch-registry: false  #是否要拉取其他服务的信息，默认是true
    #register-with-eureka: false   #是否注册自己的信息到eurekaserver 默认是true

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS