server:
  port: 10086
spring:
  application:
    name: eurekaserver
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
    fetch-registry: false  #是否要拉取其他服务的信息，默认是true
    #register-with-eureka: false  #是否注册自己的信息到eurekaserver 默认是true